console.log("=== HOISTING ===\nhoisting is a community coined term describing how variable and function declarations appear to move to the top of their scope before execution.\nit is not an official ECMAScript keyword.\njavascript does not physically move code upward.\ninstead, during the memory creation phase, javascript allocates memory for variables and functions before executing code.\nvar variables are initialized as undefined, while function declarations are fully stored in memory.\nthis behavior explains why functions can sometimes be called before their definitions.\n");

// | Type                 | Hoisted? | Initial Value |
// | -------------------- | -------- | ------------- |
// | `var`                | ✅        | `undefined`   |
// | function declaration | ✅        | full function |
// | `let`                | ✅        | TDZ           |
// | `const`              | ✅        | TDZ           |

console.log("=== REALITY OF HOISTING ===\njavascript does not physically move code during hoisting.\ninstead, before execution begins, javascript performs a memory creation phase.\nduring this phase, memory is allocated for variables and functions.\nvariables declared with var are initialized as undefined, while function declarations are fully stored in memory.\nthis is why variables and functions can sometimes be accessed before their actual position in the code.\nhoisting is essentially a result of memory allocation happening before code execution.\n");

console.log("=== VARIABLE HOISTING ===\nvariables declared with var are hoisted and initialized as undefined during memory creation.\naccessing them before assignment returns undefined instead of an error.\nlet and const are also hoisted, but they remain in the Temporal Dead Zone (TDZ) until initialization.\naccessing let or const variables before initialization throws a ReferenceError.\nundefined means a variable exists in memory but has not yet received a value.\nnot defined means the variable was never declared at all.\n");

console.log("=== FUNCTION DECLARATION HOISTING ===\nfunction declarations are fully hoisted during the memory creation phase.\nthe entire function body is stored in memory before code execution begins.\nthis allows function declarations to be called before their actual position in the code.\nexample: greet(); function greet() {} works successfully.\nthis behavior is different from variable hoisting because variables declared with var are only initialized as undefined.\nfunction expressions are not fully hoisted because they behave like normal variable assignments.\n");

console.log("=== FUNCTION EXPRESSIONS ===\nfunction expressions occur when a function is assigned to a variable.\nexample: const greet = function() {}.\nfunction expressions are not fully hoisted like function declarations.\ninstead, they follow the hoisting rules of the variable keyword used.\nwith var, the variable is initialized as undefined.\nwith let and const, the variable stays inside the Temporal Dead Zone (TDZ) until initialization.\ncalling a function expression before initialization can result in TypeError or ReferenceError depending on the declaration type.\narrow functions are also function expressions and follow the same hoisting behavior.\n");

console.log("=== FUNCTION DECLARATION VS EXPRESSION ===\nfunction declarations use syntax like: function greet() {}.\nthey are fully hoisted, meaning the entire function is available before execution starts.\nfunction expressions store functions inside variables.\nexample: const greet = function() {}.\nfunction expressions follow normal variable hoisting rules instead of full function hoisting.\nwith const and let they stay inside the Temporal Dead Zone (TDZ) until initialization.\nwith var they are initialized as undefined.\narrow functions are also function expressions.\n");

console.log("=== ANONYMOUS FUNCTIONS ===\nan anonymous function is a function without a name.\nexample: function() {}.\nanonymous functions are commonly used inside function expressions and callbacks.\nexample: const greet = function() {}.\nthey are useful for temporary logic where a reusable function name is unnecessary.\nanonymous functions are heavily used in timers, event listeners, and array methods.\narrow functions are also commonly anonymous.\n");

console.log("=== IIFE ===\nIIFE stands for Immediately Invoked Function Expression.\nit is a function expression that executes immediately after being created.\nsyntax: (function() { })().\nthe outer parentheses convert the function into an expression, and the final () immediately invokes it.\nIIFEs were commonly used to create private scope and avoid polluting the global scope.\nvariables declared inside an IIFE are not accessible outside it.\nmodern javascript uses let, const, and modules for similar scoping benefits, so IIFEs are less common today.\n");