// http://latentflip.com/loupe/?code=JC5vbignYnV0dG9uJywgJ2NsaWNrJywgZnVuY3Rpb24gb25DbGljaygpIHsKICAgIHNldFRpbWVvdXQoZnVuY3Rpb24gdGltZXIoKSB7CiAgICAgICAgY29uc29sZS5sb2coJ1lvdSBjbGlja2VkIHRoZSBidXR0b24hJyk7ICAgIAogICAgfSwgMjAwMCk7Cn0pOwoKY29uc29sZS5sb2coIkhpISIpOwoKc2V0VGltZW91dChmdW5jdGlvbiB0aW1lb3V0KCkgewogICAgY29uc29sZS5sb2coIkNsaWNrIHRoZSBidXR0b24hIik7Cn0sIDUwMDApOwoKY29uc29sZS5sb2coIldlbGNvbWUgdG8gbG91cGUuIik7!!!PGJ1dHRvbj5DbGljayBtZSE8L2J1dHRvbj4%3D

console.log("=== SYNCHRONOUS VS ASYNCHRONOUS JAVASCRIPT ===\nsynchronous javascript executes code line-by-line using a single-threaded call stack.\none task must fully complete before the next task can begin.\nlong-running synchronous tasks can block the call stack and freeze the browser UI.\nthis blocking behavior occurs because javascript cannot process other tasks while the current task occupies the stack.\nasynchronous behavior allows tasks like timers, API requests, and events to be handled outside the main call stack using browser/runtime APIs and the event loop.\n");

console.log("=== HOW SETTIMEOUT WORKS ===\nwhen javascript encounters setTimeout(), it does not keep waiting inside the call stack.\ninstead, the timer handling is delegated to browser/runtime Web APIs.\nthis allows the main javascript thread to continue executing synchronous code without blocking.\nafter the timer completes, the callback moves into the callback queue.\nthe event loop waits for the call stack to become empty before pushing the callback back onto the stack for execution.\nthis architecture enables asynchronous, non-blocking behavior even though javascript itself is single-threaded.\n");

// JavaScript Engine
//       +
// Runtime Environment
//       =
// Asynchronous JavaScript

console.log("=== JAVASCRIPT RUNTIME ENVIRONMENT ===\nasynchronous javascript relies on runtime environment components outside the core javascript engine.\nkey components include the call stack, Web APIs/runtime APIs, callback queue, and event loop.\nthe call stack executes synchronous javascript code.\nWeb APIs provided by browsers or Node.js handle asynchronous operations like timers, fetch requests, and DOM events.\nwhen async tasks complete, their callbacks move into the callback queue.\nthe event loop continuously checks whether the call stack is empty and moves queued callbacks back onto the stack for execution.\n");

console.log("=== WEB APIs ===\nWeb APIs are features provided by the browser or runtime environment outside the core javascript engine.\nexamples include setTimeout(), fetch(), DOM events, and localStorage.\nWeb APIs handle asynchronous operations independently of the call stack.\nthis prevents javascript's single-threaded execution from blocking while waiting for timers, network requests, or user events.\nafter async operations complete, callbacks move into the callback queue and later return to the call stack through the event loop.\n");

console.log("=== CALLBACK QUEUE ===\nwhen asynchronous tasks like setTimeout() complete, their callback functions are moved into the callback queue.\ncallbacks do not execute immediately after completion.\nthey must wait until the call stack becomes empty.\nthe event loop continuously checks the call stack and moves queued callbacks onto the stack when possible.\nthe callback queue follows FIFO (First In First Out) order.\nthe queue itself only stores waiting callbacks; actual execution still happens inside the call stack.\n");

console.log("=== EVENT LOOP ===\nthe event loop continuously monitors the call stack and the callback queue.\nit checks whether the call stack is empty and whether callbacks are waiting in the queue.\nif both conditions are true, the event loop moves a callback from the callback queue into the call stack for execution.\nthe event loop enables asynchronous javascript behavior while preserving single-threaded execution.\nit never interrupts currently running synchronous code.\n");

console.log("=== JAVASCRIPT EXECUTION MODEL ===\nweb APIs allow asynchronous tasks like timers and network requests to run outside the call stack, keeping javascript responsive and non-blocking.\nsetTimeout(delay) only guarantees a minimum waiting time, not exact execution timing.\nif the call stack remains busy with synchronous code, completed callbacks must continue waiting in the callback queue.\ncallbacks execute only after the call stack becomes empty and the event loop moves them back onto the stack.\nthe interaction between the call stack, Web APIs, callback queue, and event loop forms the complete javascript execution model.\n");